language: python
python:
  - "2.7"
install: pip install -r requirements-dev.txt && pip install -e . && ./instance/manage.py collectstatic --noinput
script:  ./instance/manage.py test nbsap
after_success: coveralls
notifications:
  email:
    recipients:
      - purepython@eaudeweb.ro
