version: '2'

services:
  nginx:
    image: nginx:1.13-alpine
    container_name: tct.static
    environment:
      NGINX_CONF: |-
        server {
          listen 80;

          access_log /var/log/nginx/access.log main;

          location /static {
            sendfile on;
            tcp_nopush on;
            gzip on;
            gzip_types text/plain application/x-javascript text/css;
            expires 1d;
            root /var/local/tct;
          }
        }
    depends_on:
    - base
    volumes:
    - static-files:/var/local/tct/static:ro
    command: /bin/sh -c 'echo "$$NGINX_CONF" > /etc/nginx/conf.d/default.conf && exec nginx -g "daemon off;"'

  app:
    image: eeacms/tct-biodiversity:1.7-alpine
    container_name: tct.app
    ports:
    - "8000:80"
    depends_on:
    - postgres
    environment:
      DEBUG: 'True'
    env_file:
    - ./docker/postgres.env
    - ./docker/demo.env
    volumes:
    - static-files:/var/local/tct/static

  postgres:
    image: postgres:9-alpine
    container_name: tct.db
    env_file:
    - ./docker/postgres.env
    volumes:
    - data:/var/lib/postgresql/data
    - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  static-files:
    driver: local
  data:
    driver: local
