version: '2'

services:
  nginx:
    image: nginx:1.11.13
    environment:
      TZ: Europe/Copenhagen
      NGINX_CONF: |-
        server {
          listen 80;

          access_log /var/log/nginx/access.log main;

          location /static {
            sendfile on;
            tcp_nopush on;
            gzip on;
            gzip_types text/plain application/x-javascript text/css;
            expires 1d;
            root /var/local/tct;
          }
        }
    depends_on:
    - base
    volumes:
    - tct-static-files:/var/local/tct/static:ro
    command: /bin/bash -c 'echo "$$NGINX_CONF" > /etc/nginx/conf.d/default.conf && exec nginx -g "daemon off;"'

  base:
    image: eeacms/tct-biodiversity:latest
    environment:
      TZ: Europe/Copenhagen
      DEBUG: 'False'
    env_file:
    - ./env-files/mysql.env
    volumes:
    - tct-static-files:/var/local/tct/static

  demo:
    extends:
      service: base
    ports:
    - "8000:80"
    depends_on:
    - mysql
    environment:
      DEBUG: 'True'
    env_file:
    - ./env-files/mysql.env
    - ./env-files/demo.env

  mysql:
    image: mysql:latest
    environment:
      TZ: Europe/Copenhagen
    env_file:
    - ./env-files/mysql.env
    volumes:
    - data:/var/lib/mysql
    command: "--character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci"


volumes:
  tct-static-files:
    driver: local
  tct-apache-files:
    driver: local
  tct-apache-htdocs:
    driver: local
  data:
    driver: local
